apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: inference
        image: neurotrade/inference:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "500m"
          limits:
            cpu: "1000m"
        volumeMounts:
        - name: model-volume
          mountPath: /app/models
      volumes:
      - name: model-volume
        emptyDir: {}
