apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
  namespace: neurotrade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: neurotrade-role
                operator: In
                values:
                - inference
      containers:
      - image: 192.168.1.200:30000/neurotrade/inference:latest
        name: inference
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: inference
  namespace: neurotrade
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: inference
  type: NodePort
