apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: neurotrade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: 192.168.1.200:30000/redis:7
        name: redis
        ports:
        - containerPort: 6379
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: neurotrade-role
                operator: In
                values:
                - inference    
      
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: neurotrade
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
