apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer
  namespace: neurotrade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trainer
  template:
    metadata:
      labels:
        app: trainer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: neurotrade-role
                operator: In
                values:
                - trainer
      containers:
      - image: 192.168.1.200:30000/neurotrade/trainer:latest
        name: trainer
        ports:
        - containerPort: 8001
        resources:
          limits:
            nvidia.com/gpu: 1
        
---
apiVersion: v1
kind: Service
metadata:
  name: trainer
  namespace: neurotrade
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: trainer
  type: ClusterIP