symbol: "btcusdt"
interval: 3  # seconds
max_candles: 500

redis:
  host: "redis"
  port: 6379

strategy:
  path: "configs/strategy.yaml"

model:
  path: "model.pt"

keys:
  ohlcv: "ohlcv:{symbol}:{interval}s"
  signal: "signal_history:{symbol}"
  experience: "experience_queue"
